default: qtrak_preprocess

bin:
	mkdir -p bin

src/QTRAK/qtrak_common/FFGrab.mexmaci64: src/QTRAK/qtrak_common/FFGrab.cpp
	${MATLAB_ROOT}/bin/mex \
	-I/Users/goinac/Work/misc/avbin-repos/avbin/include \
	-I/Users/goinac/Work/misc/avbin-repos/avbin/libav \
	src/QTRAK/qtrak_common/FFGrab.cpp \
	-outdir src/QTRAK/qtrak_common \
	-L/Users/goinac/Work/misc/avbin-repos/avbin/dist/macosx-x86-64 -lavbin.11 \
	-v

qtrak_preprocess: bin src/QTRAK/qtrak_preprocess/qtrak_preprocess.m src/QTRAK/qtrak_common/FFGrab.mexmaci64
	${MATLAB_ROOT}/bin/mcc \
	-v \
        -m qtrak_preprocess \
	-d bin \
	-I src/QTRAK/qtrak_preprocess \
	-I src/QTRAK/qtrak_common \
	-a src/QTRAK/qtrak_common/FFGrab.mexmaci64 \
	-a src/QTRAK/qtrak_common/fhistc.mexmaci64 \
	-a src/QTRAK/qtrak_common/ProcessFrameMeanWin.m \
	-a src/QTRAK/qtrak_common/ProcessFrameCapWin.m
