bin/tutorial.o: src/tutorial.c bin
	${CC} ${CFLAGS} \
	-c $< \
	-o $@ 

bin/tutorial: bin/tutorial.o
	${LD} \
	$< \
	-arch x86_64 \
	${STATIC_LIBS} \
	${LIBS} \
        -framework CoreFoundation \
        -framework CoreVideo \
        -framework VideoDecodeAcceleration \
	-o $@ 
